name: "Wrap weth to eth"
on:
  schedule:
  - cron: "3 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
  workflow_dispatch: {}

jobs:
  actions:
    runs-on: ubuntu-22.04
    permissions: write-all
    timeout-minutes: 5
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
      
      - name: Install dependencies with pip
        run: |
          pip install web3==6.0.0
          pip install typing-extensions==4.9.0
      
      - name: Wrap weth to eth
        env:
            ADDRESS: ${{ secrets.ADDRESS }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
            POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
            BASE_RPC: ${{ secrets.BASE_RPC }}
            ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
            BLAST_RPC: ${{ secrets.BLAST_RPC }}
            ETHEREUM_RPC_2: ${{ secrets.ETHEREUM_RPC_2 }}
            POLYGON_RPC_2: ${{ secrets.POLYGON_RPC_2 }}
            BASE_RPC_2: ${{ secrets.BASE_RPC_2 }}
            ARBITRUM_RPC_2: ${{ secrets.ARBITRUM_RPC_2 }}
            BLAST_RPC_2: ${{ secrets.BLAST_RPC_2 }}
        run: |
          python wrap_weth_to_eth.py
          echo "## Wraping weth" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
